### ISSUE TITLE
Defprotocol/Deftype don't support multi-arity functions

### ISSUE THREAD

**Issue by halgari** [pixie-lang/pixie#124]
This currently doesn't work:

`(defprotocol Foo (bar [this]) (bar [this i]))`

We should figure out how to handle this sort of code.

**Comment by thomasmulvaney** [comment]
`(defprotocol Foo (bar [this]) (bar [this i]))` doesn't work in Clojure either. You get a `Function bar in protocol Foo was redefined` error.

I think the correct syntax might be `(defprotocol Foo (bar [this] [this i]))`, unless you intend to introduce that as a complementary syntax?

When it comes to extending the protocol to a type, Pixie currently supports: 

```
(extend-type String 
  Foo 
  (bar ([this] (str "1-arity bar: " bar)) 
       ([this i] (str "2-arity bar:" bar))
```

This just produces a normal `MultiArityFn`, but no checks are done to make sure the signatures match those defined in the protocol (does Clojure do this check?).

Perhaps, a macro could turn

```
  (bar [this] (str "1-arity bar: " bar)) 
  (bar [this i] (str "2-arity bar:" bar))
```

into the multiarity version above which does work.

**Comment by halgari** [comment]
I'm fine with the `(bar ([this]) ([this i] ...))` syntax, closing
