### ISSUE TITLE
Transient vector `pop()`

### ISSUE THREAD

**Issue by chrsan** [pixie-lang/pixie#162]
I was just skimming through the code to learn more about this cool project and I think I've spotted something. It looks like the line linked below is wrong:

https://github.com/pixie-lang/pixie/blob/master/pixie/vm/persistent_vector.py#L355

I think it should be:

```python
if self._cnt == 1:
```

**Comment by halgari** [comment]
I think this was fixed recently? We have tests around pop now, so I'm assuming it works.
