### ISSUE TITLE
Docstring support for native functions

### ISSUE THREAD

**Issue by gyim** [pixie-lang/pixie#164]
I wanted to add docstring support to NativeFn functions, but I realized that there is a difference between how Pixie and Clojure handles docstring metadata. I do not know whether this difference is intentional, so I thought it would be better to discuss it before making any changes.

In Clojure the docstring is read from the metadata of the var. A var "inherits" its metadata from the name of the var:

    user=> (def ^{:doc "foo"} x ^{:doc "bar"} [])
    #'user/x
    user=> (meta (var x))
    {:ns #<Namespace user>, :name x, :file "NO_SOURCE_PATH", :column 1, :line 1, :doc "foo"}
    user=> (meta x)
    {:doc "bar"}

In Pixie the docstring is read from the metadata of the contained value, and the var does not have any metadata by default:

    user => (def ^{:doc "foo"} x ^{:doc "bar"} [])
    <inst pixie.stdlib.Var>
    user => (meta (var x))
    nil
    user => (meta x)
    {:doc "bar", :line-number 39, :line <inst pixie.stdlib.LinePromise>, :column-number 36, :file "<unknown>"}

The problem is that just as in Clojure, not all values in Pixie can hold metadata (for example, NativeFn objects cannot). Unlike in Clojure, this could be changed because Pixie does not have to deal with "native" types like java.lang.String.

My question is: which path would be preferable? Should all types be able to hold metadata? Should Pixie read the docstring from the value (and lose compatibility with Clojure when writing documentation to a var that is not a function), or is it better to keep the Clojure path?

**Comment by halgari** [comment]
I'd prefer to keep metadata on the value itself. (except for numbers, that would bloat the structure too much). That way it's possible to get docstrings from values after they have been deref'ed from a var.
