### ISSUE TITLE
ns-map on a symbol blows up the VM

### ISSUE THREAD

**Issue by mac01021** [pixie-lang/pixie#166]
It does that because the ns_map implementation in pixie/vm/stdlib.py starts off by asserting that "ns" refers to an object of type namespace.

The body of the function following that assertion obviously intends to support symbols as well but, when you remove the assertion, the RPython compiler fails to compile the VM (it complains about the type of ns._registry).

I bet someone knows about this already but, since it doesn't seem to be written down anywhere, I'm adding it to the list just in case.

I will also look into this issue myself but, since I'm a noob who just found out about pixie today, it might take forever.

**Comment by thomasmulvaney** [comment]
Hi @mac01021, the RPython type checker isn't always the smartest thing. When you remove just the assertion, RPython thinks `ns` could be an instance of `Namespace` or `None`. I wrapped the bit of code with `ns._registry` in an if statement so RPython knows that `ns` __must__ be an instance of `pixie.code.Namespace`.
