### ISSUE TITLE
Segmentation faults when using "reduce"

### ISSUE THREAD

**Issue by yellowbean** [pixie-lang/pixie#175]
Hi, I assume this is not a bug ? or pixie didn't implement same as clojure does ?
```lisp
(reduce + (range 100))
```
There will be a Segmentation faults error

Regards

**Comment by heyLu** [comment]
I think this is a bug, it should work. I don't know when I have time to look into this, but for now `(reduce + 0 (range 100))` and `(transduce + (range 100))` both work.

I'm not sure why you get a "Segmentation fault" error though, I get an exception complaining about the number of arguments.

**Comment by yellowbean** [comment]
just give some background setting
64bit, Ubunt 14.04 LTS

**Comment by andrewchambers** [comment]
can confirm, segfault in repl with jit enabled on arch linux 64 bit, fresh pypy download.

**Comment by andrewchambers** [comment]
no jit, works fine with runtime exception.
