### ISSUE TITLE
An Index function

### ISSUE THREAD

**Issue by gigasquid** [pixie-lang/pixie#179]
An new index function that will take advantage of pixie performance and give us a more feature rich nth.

`(index coll n)`

The difference between nth and index would be that you could give it negative numbers.
If given a negative number, it would take the result from the end of the list, rather than the front.

Example: 
```clojure
(index [1 2 3 4] 2) ;=> 3

(index [1 2 3 4 5 6 7] -2) ;=> 6
```

More discussion here
https://github.com/pixie-lang/pixie/pull/174

Note: this would get rid of the over-specialized `penultimate`

**Comment by rab** [comment]
:sad and kill antepenultmate and preantepenultimate for sure!

Sure, we could get together and pair on it.

**Comment by gigasquid** [comment]
Great :) I will ping you about getting together.

**Comment by thomasmulvaney** [comment]
Sounds like a great idea! But, 'index' to me sounds like either creating an index or getting the 'index' of something eg. `(= (index [:a :b :c] :c) 2)`. May be a slightly, more get-ish name could be better?

**Comment by halgari** [comment]
I agree, the name isn't set in stone. Feel free to suggest better ones.

**Comment by gigasquid** [comment]
What about `p-nth` for pixie-nth (or python like nth) depending on what frame of mind you are in?

**Comment by adder** [comment]
Hi. I'm following pixie development for a little while now, interesting stuff.

Why not  just replacing nth for the sake  of having a clean set of core functions?
 Or is their a major performance loss  in doing so?

**Comment by thomasmulvaney** [comment]
@gigasquid  I saw you mentioned `ith` in the IRC logs which i reckon is a good name. Short and sweet and sounds like it acts like `nth`.

**Comment by gigasquid** [comment]
:+1:
