### ISSUE TITLE
while/ take-while

### ISSUE THREAD

**Issue by zachcp** [pixie-lang/pixie#181]
I notice that while and take-while are not in the pixie standard library. Not sure if that was intentional or not but it looks like a straight translation from clojure would work.  

I was thinking of  using `take-while` on the buffer of strings to write a `readlines` function. and just thought those could be handy.

**Comment by halgari** [comment]
Sure, this sort of stuff is always welcome, send a PR.

**Comment by heyLu** [comment]
Thanks @zachcp for implementing this!
