### ISSUE TITLE
Stdio

### ISSUE THREAD

**Issue by thomasmulvaney** [pixie-lang/pixie#206]
Having access to stdin, stdout and stderr file pointers would be handy.

**Comment by halgari** [comment]
Agreed, we need this. Can we leverage FFI to gain access to these? I'm not exactly sure how we would gain access to these as I think they are global pointers. Perhaps I should extend ffi-infer to support non-const globals.

**Comment by andrewchambers** [comment]
3 global C getters could be added.

**Comment by thomasmulvaney** [comment]
Could we hook into rpythons RFile for this type of thing? It seems to use
rffi to get the file pointers for stdio. Maybe we could just create a File
type in Pixie which could wrap a RFile or around rffi file pointers?

**Comment by heyLu** [comment]
Mhh... the follow "works" on my machine. (Where "works" is defined as doesn't crash and prints out something. I haven't tried reading from `STDIN`, though.)

```
$ pixie-vm
Pixie 0.1 - Interactive REPL
(linux, gcc)
:exit-repl or Ctrl-D to quit
----------------------------
user => (def fdopen (ffi-fn libc "fdopen" [CInt CCharP] CVoidP))
<inst pixie.stdlib.Var>
user => (def fputs (ffi-fn libc "fputs" [CCharP CVoidP] CInt))
<inst pixie.stdlib.Var>
user => (def STDIN (fdopen 0 "r"))
<inst pixie.stdlib.Var>
user => (def STDOUT (fdopen 1 "w"))
<inst pixie.stdlib.Var>
user => (def STDERR (fdopen 1 "w"))
<inst pixie.stdlib.Var>
user => (fputs "all is well\n" STDOUT)
all is well
1
user => (fputs "maybe this is an error?\n" STDERR)
maybe this is an error?
1
```

**Comment by thomasmulvaney** [comment]
@heyLu I tried reading from STDIN, with great success:

```
Pixie 0.1 - Interactive REPL
(linux, gcc)
:exit-repl or Ctrl-D to quit
----------------------------
user => (require pixie.io :as io)
nil
user => (def fdopen (ffi-fn libc "fdopen" [CInt CCharP] CVoidP))
<inst pixie.stdlib.Var>
user => (def STDIN (fdopen 0 "r"))
<inst pixie.stdlib.Var>
user => (loop [x 0] (let [input (io/read-line (io/->FileStream STDIN))] (println "YOU TYPED: " input)) (recur (inc x)))
hi
YOU TYPED:  hi
this is read from stdin
YOU TYPED:  this is read from stdin
```

**Comment by andrewchambers** [comment]
I don't know how portable that is... Generally on a posix system you need to use STDIN_FILENO etc.

Besides, having two FILE* to the same underlying fd is just weird. All that is needed is this:

```
FILE *Stdin() { return stdin; }
```

**Comment by thomasmulvaney** [comment]
So I've had a play around with the FFI stuff and getting `STDIN_FILENO` out of `stdio.h` is easy enough using `(defconst STDIN_FILENO)`. This is great for doing stuff with all the `pixie.io-blocking` code. Doing stuff with `pixie.io` is another story. Libuv doesn't like file descriptors in general. Libuv defines std* streams as `uv_stream_t` streams which can be pulled out of a `uv_stdio_container_t`. 

My question is do we want to provide different `std*` objects for blocking and non-blocking code, or can we some how make something compatible with both? Also - there seems to be a lot of pixie development going on around non-blocking stuff so maybe we should just support that?

**Comment by halgari** [comment]
Libuv has TTY support, perhaps we can use that? http://docs.libuv.org/en/latest/tty.html

**Comment by halgari** [comment]
TTY support has been added.
