### ISSUE TITLE
Create a makefile entry for release

### ISSUE THREAD

**Issue by halgari** [pixie-lang/pixie#207]
We should create a build option in the Makefile that will do the following:

1) Build via build_with_jit
2) run tests
3) compile all src files via compile_src
4) copy all dlls, .pxi files and .pxic files (excepting tests) into a separate directory
5) create a tarball with the naming convention pixie-`uname -s`-`uname -m`.tar.bz2

Our first release should support the following:

OSX 64bit
Linux 32bit x86
Linux 64bit x86
Linux ARM

We should be able to make the build script generic enough so we can simply run the make file on a host machine to generate the binaries.

**Comment by heyLu** [comment]
Done in #269, except Linux 32bit x86. The Makefile tasks aren't generic yet, though.

**Comment by halgari** [comment]
Closing, as we'll create new tickets for creating/uploading releases.
