### ISSUE TITLE
Suggestion re: build notes on OSX

### ISSUE THREAD

**Issue by pmagwene** [pixie-lang/pixie#213]
You might add a brief note to the README that if building on OS X one must install the command line Xcode tools, even if Xcode is already installed, using the command below before doing `make build_with_jit`

```
xcode-select --install
```

This is more a PyPy issue than a pixie issue, but for someone with no previous experience with PyPy it's can be confusing why the libffi headers aren't being properly found even if they are clearly installed.

**Comment by MatthewWest** [comment]
This has been resolved, can someone please close it?

**Comment by MatthewWest** [comment]
Someone close the issue please?

**Comment by heyLu** [comment]
Here you go, somehow it slipped through. :)
