### ISSUE TITLE
Externals should be made within the project

### ISSUE THREAD

**Issue by arsenerei** [pixie-lang/pixie#219]
Pixie shouldn't leak its magic into my other directories.

**Comment by andrewchambers** [comment]
fair enough, tbh I really dislike how it seemed to download some pre compiled libraries on my system even though I can install them myself.

**Comment by halgari** [comment]
If someone wants to update the build scripts so that they work properly on all supported platforms, and fulfill these goals, I'll happily accept the PR.

**Comment by heyLu** [comment]
Fixed in #229
