### ISSUE TITLE
Strange mutating behaviour with seqs

### ISSUE THREAD

**Issue by justinj** [pixie-lang/pixie#242]
@heyLu tells me this is an artifact of iterators and indeed a bug:

```clojure
user => (def sqr #(* % %))
<inst pixie.stdlib.Var>
user => (def sqrs (map sqr [1 2 3]))
<inst pixie.stdlib.Var>
user => sqrs
<inst pixie.stdlib.ShallowContinuation>
user => (vec sqrs)
[1 4 9]
user => (vec sqrs)
[]
```

**Comment by heyLu** [comment]
If you want to fix it and don't know where to start, take a look at the implementation in ClojureScript: https://github.com/clojure/clojurescript/blob/master/src/cljs/cljs/core.cljs#L4059-L4065

(We probably don't need the extra arities, though.)

**Comment by justinj** [comment]
Cool, I'll look into it.

**Comment by halgari** [comment]
yes, we should just rip out the iterator code. They weren't as fast as I was hoping, and they're not worth the trouble.
