### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by velkyel** [pixie-lang/pixie#279]
after pull and rebuild pixie. it fails at:

in internal function run_load_stdlib
in internal function load-ns
in internal function load-file
in pixie function main
in pixie/stdlib.pxi at 310:9
(extend -at-end? Nil (fn [_] true))
        ^
RuntimeException: Var -at-end? is undefined

**Comment by andrewchambers** [comment]
I get this too.

**Comment by justinj** [comment]
Have you tried cleaning your `pxic`s (with `make clean_pxic`)? I don't think that line exists in the current `master` so it might be some kind of caching problem?

**Comment by velkyel** [comment]
@justinj after make clean_pxic everything works. thanks
