### ISSUE TITLE
Integer remainder

### ISSUE THREAD

**Issue by andrewchambers** [pixie-lang/pixie#288]
Is (rem 5 2)  meant to work?  returns a double, not an integer as I had expected..

**Comment by halgari** [comment]
yes, this is a bug. It's a problem with the implementation of rem inside numbers.py. We are currently using `fmod` which emits floats. RPython also supports `%` but only for integers. So we need to special case `rem` inside numbers.py to use fmod if either operand is a float, but use `%` if both operands are integers. Shouldn't be too hard with a lookup table in the template code.  Anyone can feel free to submit a PR for this.

**Comment by MatthewWest** [comment]
I'm a bit confused as to why numbers.py:126 doesn't solve this bug. Any idea?

**Comment by heyLu** [comment]
I think it's overridden in [line 138](https://github.com/pixie-lang/pixie/blob/master/pixie/vm/numbers.py#L138), it needs a guard for that case.

**Comment by MatthewWest** [comment]
Submitted a pull request in #292

**Comment by andrewchambers** [comment]
Thanks for looking working on this. mvp :+1:
