### ISSUE TITLE
timing function like Clojure's time

### ISSUE THREAD

**Issue by jkleiser** [pixie-lang/pixie#296]
It would be nice to have a function like 'time' for timing purposes.
http://rosettacode.org/wiki/Time_a_function#Clojure

**Comment by thomasmulvaney** [comment]
@justinj has done some work on this in https://github.com/justinj/bumblebee maybe that stuff could get merged into core.

**Comment by heyLu** [comment]
I think we should add `time` and leave everything else to libraries.

An (unreliable) `time` implementation was posted [here](https://github.com/pixie-lang/pixie/issues/165#issuecomment-73505696).  I think a real implementation may have to use something from libuv.

**Comment by thomasmulvaney** [comment]
Ok i've got something which does this in #299 using libuv.

**Comment by MatthewWest** [comment]
Can we close this issue now, since it's resolved?

**Comment by jkleiser** [comment]
There’s only one small detail. I would suggest you put a space before “ms”, as I think “99.999 ms” looks better than “99.999ms”. Just my taste. ;-)

/Jon

On 23. apr. 2015, at 19.19, Matthew West <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we close this issue now, since it's resolved?

**Comment by thomasmulvaney** [comment]
I think this can be closed now.

**Comment by heyLu** [comment]
Yes, thanks!
