### ISSUE TITLE
Reduce arities

### ISSUE THREAD

**Issue by MatthewWest** [pixie-lang/pixie#302]
I noticed this when I tried to run

    (reduce + (range 1000))

and it failed. It appears that pixie only supports one arity of reduce:

    (reduce + 0 (range 1000))

Is this an intentional design choice, or an oversight?

**Comment by thomasmulvaney** [comment]
I looked at this in #176 if you read through the comments you'll see the suggested approach to deal with this.

**Comment by MatthewWest** [comment]
I'm confused about the conclusion of that conversation—it seemed like the conclusion people reached was the one @heyLu mentioned using the function's identity:

```clojure

**Comment by halgari** [comment]
It just never got added. At the time, calling the function the wrong way caused a segfault. We fixed that, but never added the the other arity. Feel free to send a PR.

**Comment by MatthewWest** [comment]
I'm operating the assumption that functions with no 0-argument arity will give a sane exception when this arity of reduce is used. Is that a correct assumption?

**Comment by halgari** [comment]
Yes, an error will be thrown in reduce when it tries to call the reducing function with no arguments.
