### ISSUE TITLE
Pixie fails to build with the current version of PyPy

### ISSUE THREAD

**Issue by FungusHumungus** [pixie-lang/pixie#318]
Currently running 

    make build_with_jit

produces the following error 

> translation:ERROR] AttributeError: \<Struct CIF_DESCRIPTION { cif, abi, nargs, rtype, atypes, exchange_size, exchange_result, exchange_args }\> instance has no field 'exchange_result_libffi'

Running OSX 10.9.5

Using an older version of PyPy works fine.

**Comment by chunsj** [comment]
I have this problem. How can I solve this?

**Comment by halgari** [comment]
Fixed in #321 thanks to @justinj
