### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by andrewchambers** [pixie-lang/pixie#323]
Thought about using https://gitter.im ? I like Irc, But recently found its lack of persistent messages and github integration less useful than gitter.

**Comment by justinj** [comment]
I'd be up for this, with irc it's a bit annoying when you want to contact someone who isn't online (without a bot for sending messages).

**Comment by halgari** [comment]
That's fine with me.

On Thu, May 28, 2015 at 11:50 AM, Justin Jaffray <notifications@github.com>
wrote:

> I'd be up for this, with irc it's a bit annoying when you want to contact
> someone who isn't online (without a bot for sending messages).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixie-lang/pixie/issues/323#issuecomment-106524840>.
>



-- 
“One of the main causes of the fall of the Roman Empire was that–lacking
zero–they had no way to indicate successful termination of their C
programs.”
(Robert Firth)

**Comment by andrewchambers** [comment]
Cool, I think someone with write access to the repo needs to create the room. They can auto add a badge with a url. Heres what it looks like on one of my projects: https://github.com/andrewchambers/cc (scroll to readme)

**Comment by andrewchambers** [comment]
If people still want to use irc, apparently gitter rooms are also irc rooms via https://irc.gitter.im/

**Comment by andrewchambers** [comment]
@heyLu @justinj  @halgari  Could someone with write access login to gitter with github and create the room and then add the badge to the readme?

**Comment by thomasmulvaney** [comment]
Great idea. I've just set up the channel and added the badge.
