### ISSUE TITLE
Support parallel build with -j option to make.

### ISSUE THREAD

**Issue by crocket** [pixie-lang/pixie#336]
I have a quad core CPU, and I want to utilize all of the cores when I build pixie.
Right now, parallel build leads to errors.

A parallel build will boost development efforts.

This is a very profitable problem to solve without much effort.

**Comment by andrewchambers** [comment]
The majority of the pixie build time is spent in the rpython translation phase, this is single threaded and the pypy developers are aware of that issue.

**Comment by crocket** [comment]
Make can execute multiple instances of pypy. Does pypy prevent that from happening?

**Comment by andrewchambers** [comment]
The problem is the pypy translator does whole program analysis using single
threaded algorithms in a single process. Also, it is implemented in python
which has a global interpreter lock so changing to multithreaded algorithms
won't help.

**Comment by thomasmulvaney** [comment]
We can parallelize the compilation of `.pxic` files though.

```
compile_tests:
        find "tests" -name "*.pxi" | xargs -L1 -P4 ./pixie-vm -l "tests" -c
```

Adding the `-P4` parameter makes xargs compile 4 files at once.

**Comment by crocket** [comment]
@thomasmulvaney If -P option detects the number of CPU cores, it'd be optimal.

**Comment by andrewchambers** [comment]
Make has inbuilt facilities to do that already, I don't know if xargs would be a good way to do it. The problem is the makefile isn't written in a proper way.

**Comment by halgari** [comment]
Compilation of c files uses `-j` already. The rest is a limitation of the RPython compilation system. Not much else we can do.
