### ISSUE TITLE
`python` may not refer to python2 on some linux distributions.

### ISSUE THREAD

**Issue by crocket** [pixie-lang/pixie#337]
`Makefile` assumes python refers to python 2.x, which is not true on archlinux.
Thus, it leads to errors on archlinux, and I had to set PYTHON to python2 in `Makefile`.

**Comment by andrewchambers** [comment]
Yeah, that is why the makefile uses `PYTHON ?= python` You should make able to type `make PYTHON=python2`

**Comment by skrat** [comment]
I think the bigger problem here is actual dependency on Python 2. Why's that?

**Comment by emidln** [comment]
Because PyPy uses rpython (a python 2-like language built with itself and python2) and python2. python2 (or pypy2) is needed for translating the rpython source of pixie into a vm just like it is with pypy's python implementation (http://pypy.org/download.html#building-from-source).

**Comment by halgari** [comment]
Is there a way we can get the makefile to autodetect and switch to python2 if python==python3?

Or should we just default to python2 from the start?

**Comment by heyLu** [comment]
I think we should just default to python2.  The `make PYTHON=<whatever>` option can be used for other names.
