### ISSUE TITLE
Running compiled code

### ISSUE THREAD

**Issue by MatthewWest** [pixie-lang/pixie#346]
I'm unsure whether I'm running .pxic code correctly, and as a result I'm unable to test my code for BigInteger reading and writing to pxic. Currently my steps to run compiled code are:

    pixie-vm -c tests/pixie/tests/test-numbers.pxi
    pixie-vm tests/pixie/tests/test-numbers.pxic

Those steps lead to the following error:
```
RuntimeException: :pixie.stdlib/InternalError Internal error: <UnicodeDecodeError object at 0x1004faf88>

Segmentation fault: 11
```

Am I running the compiled code wrong?

**Comment by heyLu** [comment]
Pixie picks up the compiled bytecode [automatically](https://github.com/pixie-lang/pixie/blob/master/pixie/vm/stdlib.py#L410-L412).  In fact, it will currently always load a `.pxic` file if one is present, even if it is older than the `.pxi` file of the same name/path.

To run the compiled code you simple run as usual.  (After compiling with `-c` first, of course.)

**Comment by MatthewWest** [comment]
This isn't actually doing this in practice, even though I see where you're referring to that it ought to pick up a `.pxic` file, but it's not actually working. Example commands:

```bash
echo '(println "compiled")' > test.pxi
./pixie-vm -c test.pxi
echo '(println "interpreted")' > test.pxi
./pixie-vm test.pxi
```

If this were running the .pxic file, it would print "compiled." Instead, it always prints "interpreted.

**Comment by halgari** [comment]
I think this is a bug in the main loop of the pixie interpreter. If you
feed it a file name, it will always use that file. IIRC, .pxic files are
only picked up in `load-library` which is used by `require`.

On Wed, Jul 8, 2015 at 8:23 AM, Matthew West <notifications@github.com>
wrote:

> This isn't actually doing this in practice, even though I see where you're
> referring to that it ought to pick up a .pxic file, but it's not actually
> working. Example commands:
>
> echo '(println "compiled")' > test.pxi
> ./pixie-vm -c test.pxiecho '(println "interpreted")' > test.pxi
> ./pixie-vm test.pxi
>
> If this were running the .pxic file, it would print "compiled." Instead,
> it always prints "interpreted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixie-lang/pixie/issues/346#issuecomment-119595534>.
>



-- 
“One of the main causes of the fall of the Roman Empire was that–lacking
zero–they had no way to indicate successful termination of their C
programs.”
(Robert Firth)

**Comment by MatthewWest** [comment]
In testing, I just discovered that it does load the compiled file also when using `load-file` from the repl. That's good enough that it'll allow me to test.

**Comment by MatthewWest** [comment]
I'm going to open a separate issue for behavior in running scripts.
