### ISSUE TITLE
Provide a better way to run .pxic files

### ISSUE THREAD

**Issue by MatthewWest** [pixie-lang/pixie#347]
Currently, running a pixie file using `pixie-vm foo.pxi` will not look for a `.pxic` file. This is a reasonable behavior, and perhaps should be the behavior. However, there does need to be a clear way to run compiled files.

Edit: the current way to run compiled files is to load a file using require, or load-library, or load-file. Loading the file which has a `.pxi` extension will automatically find a `.pxic` extension file of the same name.

**Comment by halgari** [comment]
Fixed in master
