### ISSUE TITLE
[Question] Can pixie be used to write kernel or operating system?

### ISSUE THREAD

**Issue by crocket** [pixie-lang/pixie#353]
Someone has been writing an operating system in CommonLisp, and pixie looks like a delicious language to write an OS in.

**Comment by andrewchambers** [comment]
It is probably possible, though I would say very difficult. Pixie requires a lot of runtime support which would all need to be re implemented in kernel space. You would would probably spend weeks/months be battling with writing a new rpython backend. Not for the faint or heart.

I more sane approach might be to use the linux kernel but then write userspace in pixie if you wanted to.

**Comment by arrdem** [comment]
There have been prior efforts to write Python operating systems, notably [cleese](https://github.com/jtauber/cleese), but none of them seem especially interesting or benefit from pypy support

**Comment by heyLu** [comment]
Closing this.  If anyone *does* go further down this route, please tell us about it!
