### ISSUE TITLE
(first {:some :map}) throws RuntimeException

### ISSUE THREAD

**Issue by emidln** [pixie-lang/pixie#376]
It seems as though `(first {:some :map})` is intended to fall down to https://github.com/pixie-lang/pixie/blob/master/pixie/vm/stdlib.py#L135 which would be similar (equivalent?) to `(first (seq {:some :map}))`

This is the 

```clj
user => (first {:some :map})
ERROR: 
 in pixie function repl_fn

in /home/bja/code/pixie/pixie/repl.pxi at 24:24
               (let [x (eval form)]
                       ^
in internal function eval

in <unknown> at 2:1
(first {:some :map})
^
in pixie function first

in /home/bja/code/pixie/pixie/stdlib.pxi at 689:5
    (-first coll)))
    ^
in polymorphic function -first dispatching on pixie.stdlib.PersistentHashMap

RuntimeException: :pixie.stdlib/AssertionException No override for pixie.stdlib.PersistentHashMap on -first in protocol ISeq
```

**Comment by thomasmulvaney** [comment]
You are exactly right. The implementation of `first` as defined in RPython attempts to turn anything which is not a seq into one, calling first on the resulting sequence. This is the correct approach. However, that version is replaced by the one defined in https://github.com/pixie-lang/pixie/blob/master/pixie/stdlib.pxi#L681 which doesn't attempt to call `seq`.
