### ISSUE TITLE
FFI doesn't deal with ld scripts

### ISSUE THREAD

**Issue by skrat** [pixie-lang/pixie#377]
So a fresh clone of pixie, when being built, will fail to compile stdlib, because on some systems (arch linux), `libm.so` is a ld script instead of ELF binary.

This might be relevant: http://www.gossamer-threads.com/lists/python/dev/941581

**Comment by heyLu** [comment]
I had just happen to me as well.  Not sure how to handle it, though.  We could add a helper similar to the one for libc, but maybe we *should* handle it properly.

Here's how we find the correct libc location:

- [pixie.platform](https://github.com/pixie-lang/pixie/blob/master/pixie/vm/libs/platform.py#L12) uses `get_libc_name` from `rpython.rlib.clibffi`
- [rpython.rlib.clibffi](https://bitbucket.org/pypy/pypy/src/3c4e18e306563b898af58b332852c0c8e67ff758/rpython/rlib/clibffi.py?fileviewer=file-view-default#clibffi.py-289) uses `ctypes.util.find_library`
- and finally, `find_library` does some [dark magic involving gcc](https://hg.python.org/cpython/file/8f91b475c2fd/Lib/ctypes/util.py#l96)
    - which seems to boil down to executing `gcc -Wl,-t -o $tmpfile -l$library_name` and grepping for the full path in the result
    - we can't use `ctypes.util.find_library` (I think), because it's code from python.  we *can* use it during translation, but not at runtime

That's all I've got!  If anyone wants to do this, or has other ideas for *how* to do it, please say so.

**Comment by heyLu** [comment]
The (dirty) fix is to hard code the name of `libm` in `stdlib.pxi`:

```diff
diff --git a/pixie/stdlib.pxi b/pixie/stdlib.pxi
index 880efd4..6a82bb7 100644
--- a/pixie/stdlib.pxi
+++ b/pixie/stdlib.pxi
@@ -19,7 +19,7 @@
 (def fopen (ffi-fn libc "fopen" [CCharP CCharP] CVoidP))
 (def fread (ffi-fn libc "fread" [CVoidP CInt CInt CVoidP] CInt))
 
-(def libm (ffi-library (str "libm." pixie.platform/so-ext)))
+(def libm (ffi-library (str "libm.so.6" #_pixie.platform/so-ext)))
 (def atan2 (ffi-fn libm "atan2" [CDouble CDouble] CDouble))
 (def floor (ffi-fn libm "floor" [CDouble] CDouble))
 (def lround (ffi-fn libm "lround" [CDouble] CInt))
```

After that run `make clean_pxic compile_basics` and stuff should work.  (However, the `pixie.math` namespace does not, it would need a separate fix.)

**Comment by 12foo** [comment]
Hi, I just submitted a pull request to fix this upstream in PyPy (wanted to try out Pixie on Arch). Will update if they accept it.

**Comment by 12foo** [comment]
PR has been accepted upstream and Pixie now builds from a fresh checkout on Arch Linux. I've checked the math namespace, and that seems to work too:

```
user => (require pixie.math :as m)
[ compiling stuff... ]
nil
user => (m/log 20)
-741.444340
user =>
```

**Comment by 12foo** [comment]
Er, except that result is obviously wrong. Can somebody confirm that this is what was meant by "not working"?

**Comment by thomasmulvaney** [comment]
Fixing upstream - that is dedication to trying out Pixie! I believe that
the issue is perhaps a float is expected?  `(m/log 20.0)` seems to give me
the expected result.

Thanks for fixing this!

**Comment by 12foo** [comment]
You're right-- it works if I explicitly use a float. Phew. For a second I thought the ldscript loading somehow created a really insidious bug.

**Comment by thomasmulvaney** [comment]
@12foo I believe we should be able to make it work with Integers as well. If you have a look at https://github.com/pixie-lang/pixie/blob/master/pixie/vm/libs/ffi.py#L383 we have a bunch of ways to set various pixie types as Char pointers. It should be possible to do similiar for Doubles https://github.com/pixie-lang/pixie/blob/master/pixie/vm/libs/ffi.py#L361 so `Integers` will automatically be converted to `Doubles` when they are expected.

**Comment by heyLu** [comment]
@12foo Thanks a lot for fixing this upstream! :sparkles:

Confirmed this to work with a new checkout of pypy.  (`rm -r externals` and rebuild to update it.)
