### ISSUE TITLE
Fail to build on (x)ubuntu

### ISSUE THREAD

**Issue by KronXIII** [pixie-lang/pixie#398]
On a fresh install I get the following error :

    $ PYTHON="/usr/bin/python" make build_with_jit 
    [...]
    tar -jxf /tmp/externals.tar.bz2 --strip-components=2
    /usr/bin/python: can't open file 'externals/pypy/rpython/bin/rpython': [Errno 2] No such file or directory

which makes the build fail.
When I manually run the tar command on tmp/externals.tar.bz2 I can find no trace of the pypy/* files.
apt-get'ing pypy, libuv-dev & libffi-dev changes nothing. 
What am I doing wrong?

**Comment by heyLu** [comment]
You're not doing anything wrong.  Can you post the full log?

**Comment by KronXIII** [comment]
$ PYTHON="/usr/bin/python" make build_with_jit 
    echo https://github.com/pixie-lang/external-deps/releases/download/1.0/`uname -s`-`uname -m`.tar.bz2
    https://github.com/pixie-lang/external-deps/releases/download/1.0/Linux-x86_64.tar.bz2
    curl -L https://github.com/pixie-lang/external-deps/releases/download/1.0/`uname -s`-`uname -m`.tar.bz2 > /tmp/externals.tar.bz2
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    100   583    0   583    0     0    950      0 --:--:-- --:--:-- --:--:--   949
    100  517k  100  517k    0     0   200k      0  0:00:02  0:00:02 --:--:--  421k
    tar -jxf /tmp/externals.tar.bz2 --strip-components=2
    /usr/bin/python: can't open file 'externals/pypy/rpython/bin/rpython': [Errno 2] No such file or directory
    Makefile:22: recipe for target 'build_with_jit' failed
    make: *** [build_with_jit] Error 2

I suspect a path error, but checking /tmp/externals.tar.bz2 shows no pypy/ dir, but .../pixie/externals/ does contain a pypy.tar.bz2

    $ tar -xjf externals/pypy.tar.bz2 

    bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
    bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

    It is possible that the compressed file(s) have become corrupted.
    You can use the -tvv option to test integrity of such files.

    You can use the `bzip2recover' program to attempt to recover data from undamaged sections of corrupted files.

    tar: Child returned status 2
    tar: Error is not recoverable: exiting now

**Comment by thomasmulvaney** [comment]
When the download is corrupted you have to delete the `externals` directory in order for the Makefile to redownload it. If `externals` exists the Makefile assumes everything is ok.

Hopefully that will fix everything up.

**Comment by KronXIII** [comment]
The build is progressing, this seems to have fixed it. Thank you!
