### ISSUE TITLE
No unchecked operations for +, -, *

### ISSUE THREAD

**Issue by reutermj** [pixie-lang/pixie#406]
Discussed October 22 on Gitter with Andrew Chambers.

The default behaviour of the +, -, and * math operations (to convert to BigInteger on overflow) arguably makes more since than the cyclical behaviour found in many other languages. But, there are many algorithms like the XorShift PRNG algorithm and applications like games that the cyclical behaviour makes more since or are requirements.

Having a secondary library function along the lines of u+, u-, and u* to allow for the cyclical behaviour while maintaining the default behaviour would be appreciated greatly for a lot of the applications for which I want to be using Pixie (i.e. procedural generation and games).

I have an an initial implementation of u+, u-, and u* in https://github.com/reutermj/pixie. This implementation currently works for pixie.stdlib.Integer and pixie.stdlib.Float. Currently the there are issues with the usages of pixie.stdlib.BigInteger and pixie.stdlib.Ratio. But, I can fix those, and submit a pull request if my proposed function naming and implementation of the unchecked operations are accepted.

**Comment by thomasmulvaney** [comment]
Implemented in #426
