### ISSUE TITLE
wrong return value check of fputc infile-output-rf  (via  write-byte)

### ISSUE THREAD

**Issue by mpenet** [pixie-lang/pixie#413]
https://github.com/pixie-lang/pixie/blob/master/pixie/io-blocking.pxi#L88 
I noticed that while copying image files around, some of the files would be corrupted because of this. 

I believe EOF should be -1 not 0 ? (if I change the line indicated for -1 this works as expected).

**Comment by heyLu** [comment]
Yes, that seems to be the case.  Not sure if it's -1 on all systems, though, because `man 3 fputc` only mentions the `EOF` constant, not -1 specifically.

**Comment by mpenet** [comment]
Getting to the constant would be the right way to do it indeed. But as of right now it requires going into the guts of ffi (without ffi-infer) since  ffi-infer requires io-blocking.

**Comment by mpenet** [comment]
I guess we'd have to remove all the reference to io-blocking in ffi-infer (it's just run-command and spit) to make it easy, unless you see another way.

**Comment by mpenet** [comment]
Maybe @halgari has suggestions on the way to deal with this? I'd gladly submit a PR if I get some directions.

**Comment by heyLu** [comment]
For now hard-coding -1 is fine, I think, because that would fix the bug.
