### ISSUE TITLE
date/time functions

### ISSUE THREAD

**Issue by mpenet** [pixie-lang/pixie#417]
Is there anything planned or did anyone work on date/time manipulation? Something similar to java.util.Date (simple date creation/parsing and functional getters/setters for of day/month/year etc). If not I could try to explore solutions.

**Comment by heyLu** [comment]
As far as I'm aware, nobody is working on it.  (Maybe ask on IRC/Gitter as well.)  The easiest way to experiment would be to publish a library for handling dates.

**Comment by mpenet** [comment]
That's what I had in mind, it s probably better to keep pixie very lightweight anyway (few dependencies).

**Comment by mpenet** [comment]
I put something in the wild, but it's a 20min hack and it's missing some important things (like ms resolution, proper overflow detection on add-interval etc). But it kinda works. I don't know if using basic C structs/fns is the way to go or try to rely on something more complete from the get go.

https://github.com/mpenet/aeon
