### ISSUE TITLE
printf doesn't work as expected

### ISSUE THREAD

**Issue by pfefferminz132** [pixie-lang/pixie#420]
(printf "%d" 42) gives some strange and unexpected output.

**Comment by heyLu** [comment]
Use the typical printing functions from Clojure.  (`print`, `println`, `pr` and `prn`)

Our `printf` function only accepts a single string as an argument.  Not sure if the FFI can handle the full signature for `printf` yet.  Also, `printf` returns the number of bytes written, which might contribute to the confusing output.

**Comment by pfefferminz132** [comment]
clojure has printf, too and it works like it supposed to. pixie's printf accepts more than one argument
e.g. (printf "%d and %d" 42 43). It's just not the output that one expects.
(printf "%s and %s" 42 43) segfaults.
