### ISSUE TITLE
pixie notebook?

### ISSUE THREAD

**Issue by dtolpin** [pixie-lang/pixie#433]
Is there a pixie notebook or work in progress on it? I did some work with and on Gorilla REPL, and would like to see something similar for pixie. If there is no such thing and no one is working on it, I'd just try and implement it by myself.

**Comment by heyLu** [comment]
Not that I'm aware of, no.  Feel free to work on it and tell use how far you got!  :)

**Comment by thomasmulvaney** [comment]
Closing this but feel free to report your success in the gitter channel or add it to the libraries section of the wiki https://github.com/pixie-lang/pixie/wiki/Libraries

Happy hacking!
