### ISSUE TITLE
Add an eduction type and function

### ISSUE THREAD

**Issue by thomasmulvaney** [pixie-lang/pixie#483]
Add an `Eduction` type and function to `stdlib.pxi`.

**Comment by alekcz** [comment]
@thomasmulvaney what's an `Education` type?

**Comment by thomasmulvaney** [comment]
@alekcz an `Eduction` is basically the object which is returned by calling `eduction`: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/eduction . It essentially wraps a `xform` function (just like what one can pass `into` or `transduce`) as well as a collection and provides a `IReducible` interface. It's sort of like a suspended collection + transformation. The Pixie version wouldn't have to support `Iterable` as we don't currently have that.

**Comment by thomasmulvaney** [comment]
Added thanks to @sebastiano-barrera
