### ISSUE TITLE
Error during compilation: Unexpected EOF while reading

### ISSUE THREAD

**Issue by BrunoBonacci** [pixie-lang/pixie#487]
I'm having trouble compiling a fresh installation of pixie.
I'm on Mac os X (Darwin Kernel Version 15.0.0), libuv/1.7.5, libffi/3.0.13.
So I've tried to build the project using the docker file but I'm still getting the same error:

```
(f/with-config  {:library "uv"
^
in pixie function with-config

in /usr/src/pixie/pixie/ffi-infer.pxi at 223:10
        ~(run-infer *config* @*bodies*))))
         ^
in pixie function run-infer

in /usr/src/pixie/pixie/ffi-infer.pxi at 204:18
          result (read-string (io/run-command cmd-str))
                 ^
in internal function read-string

RuntimeException: :pixie.stdlib/EOFWhileReadingException Unexpected EOF while reading

[/usr/src/pixie /usr/src/pixie/lib /usr/src/pixie/include /usr/src/pixie/../lib /usr/src/pixie/../include]
c++ -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/ffinFgyJr/ffi.cpp  -I /usr/src/pixie  -I /usr/src/pixie/lib  -I /usr/src/pixie/include  -I /usr/src/pixie/../lib  -I /usr/src/pixie/../include   -o /tmp/ffinFgyJr/ffi.out && /tmp/ffinFgyJr/ffi.out
```

Any idea on what might be wrong?

**Comment by thomasmulvaney** [comment]
You may be missing boost. Boost is required for generating the templates for FFI infer. I suspect the templates do not exist and hence the EOF.

Hope that helps.

**Comment by BrunoBonacci** [comment]
Hi,
I do have boost/1.59.0 however the compilation it is failing on the Docker as well
and as you can see the Dockerfile is including *libboost-dev*
https://github.com/pixie-lang/pixie/blob/master/Dockerfile#L5

To reproduce the error simply run:
```
docker build -t pixie .
```
in your project folder.

**Comment by thomasmulvaney** [comment]
I've done a fresh clone of pixie and successfully built the docker image on a recent version of Ubuntu and Docker 1.9.1. When you tried building without docker did you get the same error message?

**Comment by BrunoBonacci** [comment]
yes, the error message comes from the docker build.

now I'm puzzled. your local env shouldn't have any effect on the build as
it is running under a debian container
https://github.com/pixie-lang/pixie/blob/master/Dockerfile#L1
How it is possible to get two different results?

I've also made a fresh clone & build:

$ git clone https://github.com/pixie-lang/pixie.git
$ cd pixie
$ docker build -t pixie .

and I'm still getting the same.

I'll try to get a ubuntu and see if I get the same.
Bruno

**Comment by thomasmulvaney** [comment]
I'd love to be more help but unfortunately my knowledge of docker is limited.

**Comment by thomasmulvaney** [comment]
I'm trying now with the --no-cache option.

**Comment by BrunoBonacci** [comment]
Are you trying with a fresh clone or using your dev environment??
I that case the `externals/` folder could be different.

I've tried to run the same build from a clean clone in ubuntu and I get another error

![image](https://cloud.githubusercontent.com/assets/1639862/12324951/933bcd4e-babe-11e5-8303-0b2f43637339.png)

```
[pypy]
ARG INFO:  (<rpython.translator.driver.TranslationDriver object at 0x7fe1be146a10>, [])
> /usr/src/pixie/externals/pypy/rpython/tool/runsubprocess.py(87)_run()
-> assert results.startswith('(')
Traceback (most recent call last):
  File "externals/pypy/rpython/bin/rpython", line 20, in <module>
    main()
  File "/usr/src/pixie/externals/pypy/rpython/translator/goal/translate.py", line 325, in main
    debug(True)
  File "/usr/src/pixie/externals/pypy/rpython/translator/goal/translate.py", line 278, in debug
    pdb_plus_show.start(tb)
  File "/usr/src/pixie/externals/pypy/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/usr/src/pixie/externals/pypy/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
```

Have you tried to clean your *externals* before building?

**Comment by thomasmulvaney** [comment]
I did a `make clean` in a fresh clone before running the docker build but still can't reproduce the issue.

**Comment by BrunoBonacci** [comment]
no idea,

by any chance, are you guys going to deliver binary downloadable for the various platforms any time soon?

**Comment by laurio** [comment]
I had the same issue when trying to build Pixie from master (by running make clean && make build_with_jit) on Raspberry Pi 2 Model B (Linux raspberrypi 4.1.13-v7+). Posted details to Gitter pixie-lang chat also.

**Comment by thomasmulvaney** [comment]
@BrunoBonacci getting a binary out is a goal but I'm not sure when it will happen. By the way - there is a prebuilt docker image you can pull down which is built off master: `docker pull pixielang/pixie`

**Comment by BrunoBonacci** [comment]
Thanks @thomasmulvaney, that should do for the moment.

**Comment by oholiab** [comment]
Try pulling master again on OSX, https://github.com/pixie-lang/pixie/commit/6e9ec11b8608e80fc4bf817490c27666f6388909 should probably have fixed the problem.

**Comment by BrunoBonacci** [comment]
Thanks @oholiab with by pulling the latest changes it seems to have fixed the compilation issue.

thx
