### ISSUE TITLE
Make pixie 1337

### ISSUE THREAD

**Issue by bendlas** [pixie-lang/pixie#503]
As of now, the `master` branch contains 1333 commits, so we have exactly 4 commits to finish the core language. That means 4 releases before the permanent code freeze. Think about it!

- [x] Release 1334 "cosy"
- [x] Release 1335 "gozy"
- [x] Release 1336 "ohzy"
- [x] Release 1337 "frozy"

**Comment by thomasmulvaney** [comment]
@bendlas it looks like we have made it "1337" already. I forgot to tag the last four releases with the suggested names :stuck_out_tongue_winking_eye: Unfortunately a permanent freeze will make everyone very bored.
