### ISSUE TITLE
Integer overflow handling

### ISSUE THREAD

**Issue by andrewchambers** [pixie-lang/pixie#58]
Currently in pixie and integer is an integer, and a big integer is a big integer...

Is Pixie planned to have transparent promotion to arbitrary precision integers like python? or is it going  to throw an exception on overflow like clojure seems to. 

Personally I think the python method is quite nice and "just works" - Really just a language design question.

**Comment by halgari** [comment]
Currently integers simply roll over to 0 on overflow. This is quite bad. I think andrewchambers is right, we could make this fast and efficient and it's probably worth looking into. If nothing else, we should throw an exception on overflow.

**Comment by halgari** [comment]
So it looks like if we wrap all integer arithmetic in rpythin.rlib.rarithmatic.ovfcheck, it will cause a OverflowError to be thrown on overflow. For integers I think it makes sense to just auto-promote them to big ints in that case. Examples of the usage can be seen in `/pypy/pypy/objspace/std/intobject.py`.

**Comment by gyim** [comment]
I implemented this in @halgari 's previous project, clojure-metal. This is how it looks like, maybe it can help: gyim/clojure-metal@9beae46b9d23b17f59851d848f986c5a0696857a
