### ISSUE TITLE
Provide a way to print, and query stack traces

### ISSUE THREAD

**Issue by halgari** [pixie-lang/pixie#6]

**Comment by gigasquid** [comment]
Could you elaborate a bit more on what you are looking for?  I am thinking a way to print the stacktrace from the last exception?  What about the query bit?

**Comment by andrewchambers** [comment]
Functions to walk up the stack frame getting function and position information for each frame. Probably also inspect local variables in each stack frame for debugging.

**Comment by halgari** [comment]
Exactly, all the information exists in the stack trace. It'd be nice to be
able to access all the frames from within pixie. In this code the stack
trace is walked and printed:
https://github.com/pixie-lang/pixie/blob/master/pixie/vm/object.py#L114 .
It'd be nice to be able to return that as a seq with some sort of function.

Timothy

On Sun, Feb 22, 2015 at 7:39 PM, andrewchambers <notifications@github.com>
wrote:

> Functions to walk up the stack frame getting function and position
> information for each frame. Probably also inspect local variables in each
> stack frame for debugging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixie-lang/pixie/issues/6#issuecomment-75482106>.
>



-- 
“One of the main causes of the fall of the Roman Empire was that–lacking
zero–they had no way to indicate successful termination of their C
programs.”
(Robert Firth)

**Comment by andrewchambers** [comment]
A side note, I think some sort of debug-hook system + the immutability of most types could also result in some interesting things like efficient trace recording.

**Comment by gigasquid** [comment]
Cool - I will give it a look.

**Comment by halgari** [comment]
PR: #192 fixes this. Thanks gigasquid!
