### ISSUE TITLE
Plurality functions, more generic than multimethods

### ISSUE THREAD

**Issue by bmillare** [pixie-lang/pixie#96]
I noticed a first attempt for multimethods was completed. I was wondering if more discussion can be had about what multimethods are trying to solve before locking in the current implementation and goals. I've done some work on this with my plural function repository.
https://github.com/bmillare/dj.plurality

I've implemented them with metadata but I would imagine we can open up the implementation for pixie to use whatever method seems best.

(Excerpt from readme) Motivation:

We want to solve the expression problem. Multimethods do so but with limitations. It has a locked resolving algorithm and complects state and extensibility.

Plural functions were coined https://groups.google.com/forum/?fromgroups=#!topic/clojure/KC-zfUE1rXk, and I will refer to them as plural-fns. Plural-fns support any resolving algorithm and you can swap out resolving algorithm as you please (as long as you provide the transformation fn for implementations). Because plural-fns are immutable, they have less lookups than multimethods and do not implement references. This allows you to choose any reference type, like vars, atoms, or refs, to store and "mutate" the plural fn. Plural-fns are also just values making it easy to modify them like you would with hash-maps. Since they are just functions, you can create closures and dynamically generate them via higher-order functions.

**Comment by halgari** [comment]
I'm closing this as there hasn't been much discussion about it in the past few months. I'd be open to making multimethods more open. But I'd like to see a concise patch to that effect. Multimethods are pretty simple, can we add these features but keep the implementation just as simple?
